import React, { ReactElement } from "react";
import Head from "next/head";

interface Props {}

export default function index({}: Props): ReactElement {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content={"TBD Privacy Policy"} />
      </Head>

      <div className="relative px-4 overflow-x-hidden sm:px-6 lg:px-8">
        <div className="mx-auto text-lg max-w-prose">
          <h1>
            <span className="block pt-12 text-3xl font-extrabold leading-8 tracking-tight text-center text-gray-700 sm:text-4xl">
              Privacy Policy
            </span>
            <span className="block text-sm font-light tracking-wide text-center uppercase text-indigo-600">
              Effective Date: 5/24/2022
            </span>
          </h1>
        </div>

        <div className="mx-auto text-lg max-w-prose">
          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Introduction
          </h2>

          <p className="mt-4 font-light text-gray-700">
            TBD LLC (“us”, “we”, or “our”) operates www.TBD (hereinafter
            referred to as “Service”).
          </p>

          <p className="mt-4 font-light text-gray-700">
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions.
          </p>

          <p className="mt-4 font-light text-gray-700">
            Our Terms and Conditions (“Terms”) govern all use of our Service and
            together with the Privacy Policy constitutes your agreement with us
            (“agreement”).
          </p>
        </div>

        <div className="mx-auto text-lg max-w-prose">
          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Definitions
          </h2>
          <p className="mt-4 font-light text-gray-700">
            SERVICE means the www.TBD website operated by TBD LLC.
          </p>
          <p className="mt-4 font-light text-gray-700">
            USAGE DATA is data collected automatically either generated by the
            use of Service or from Service infrastructure itself (for example,
            the duration of a page visit).
          </p>
          <p className="mt-4 font-light text-gray-700">
            COOKIES are small files stored on your device (computer or mobile
            device).
          </p>
          <p className="mt-4 font-light text-gray-700">
            DATA CONTROLLER means a natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data.
          </p>
          <p className="mt-4 font-light text-gray-700">
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
          </p>
          <p className="mt-4 font-light text-gray-700">
            DATA SUBJECT is any living individual who is the subject of Personal
            Data.
          </p>

          <p className="mt-4 font-light text-gray-700">
            THE USER is the individual using our Service. The User corresponds
            to the Data Subject, who is the subject of Personal Data.
          </p>

          <p className="mt-4 font-light text-gray-700">
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
        </div>

        <div className="mx-auto text-lg max-w-prose">
          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Types of Data Collected
          </h2>

          <p className="mt-4 font-light text-gray-700">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:
          </p>

          <ul className="pl-10 mt-4 font-light text-gray-600 list-disc">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>

          <p className="mt-4 font-light text-gray-700">
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link in
            our email communications or by emailing us directly at support@TBD.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Usage Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through a mobile
            device (“Usage Data”).
          </p>
          <p className="mt-4 font-light text-gray-700">
            This Usage Data may include information such as your computer&apos;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <p className="mt-4 font-light text-gray-700">
            When you access Service with a mobile device, this Usage Data may
            include information such as the type of mobile device you use, your
            mobile device unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Location Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We may use and store information about your location if you give us
            permission to do so (“Location Data”). We use this data to provide
            features of our Service, to improve and customize our Service.
          </p>
          <p className="mt-4 font-light text-gray-700">
            You can enable or disable location services when you use our Service
            at any time by way of your device settings.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Tracking Cookies Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </p>
          <p className="mt-4 font-light text-gray-700">
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our Service.
          </p>

          <p className="mt-4 font-light text-gray-700">
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>

          <p className="mt-4 font-light text-gray-700">
            Examples of Cookies we use:
          </p>

          <ul className="pl-10 mt-4 font-light text-gray-600 list-disc">
            <li>
              Session Cookies: We use Session Cookies to operate our Service.
            </li>
            <li>
              Preference Cookies: We use Preference Cookies to remember your
              preferences and various settings.
            </li>
            <li>
              Security Cookies: We use Security Cookies for security purposes.
            </li>
            <li>
              Advertising Cookies: Advertising Cookies are used to serve you
              with advertisements that may be relevant to you and your
              interests.
            </li>
          </ul>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Use of Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            TBD LLC uses the collected data for various purposes:
          </p>

          <ul className="pl-10 mt-4 font-light text-gray-600 list-disc">
            <li>to provide and maintain our Service;</li>
            <li>to notify you about changes to our Service;</li>
            <li>
              to allow you to participate in interactive features of our Service
              when you choose to do so;
            </li>
            <li>to provide customer support;</li>
            <li>
              to gather analysis or valuable information so that we can improve
              our Service;
            </li>
            <li>to monitor the usage of our Service;</li>
            <li>to detect, prevent and address technical issues;</li>
            <li>to fulfill any other purpose for which you provide it;</li>
            <li>
              to carry out our obligations and enforce our rights arising from
              any contracts entered into between you and us, including for
              billing and collection;
            </li>
            <li>
              to provide you with notices about your account and/or
              subscription, including expiration and renewal notices,
              email-instructions, etc.;
            </li>
            <li>
              to provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information;
            </li>
            <li>
              in any other way we may describe when you provide the information;
            </li>
            <li>for any other purpose with your consent.</li>
          </ul>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Retention of Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </p>
          <p className="mt-4 font-light text-gray-700">
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this
            data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Transfer of Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </p>
          <p className="mt-4 font-light text-gray-700">
            If you are located outside United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to United States and process it there.
          </p>
          <p className="mt-4 font-light text-gray-700">
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </p>
          <p className="mt-4 font-light text-gray-700">
            TBD LLC will take all the steps reasonably necessary to ensure that
            your data is treated securely and in accordance with this Privacy
            Policy and no transfer of your Personal Data will take place to an
            organisation or a country unless there are adequate controls in
            place including the security of your data and other personal
            information.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Disclosure of Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We may disclose personal information that we collect, or you
            provide:
          </p>

          <ul className="pl-10 mt-4 font-light text-gray-600 list-disc">
            <li>
              Under certain circumstances, we may be required to disclose your
              Personal Data if required to do so by law or in response to valid
              requests by public authorities.
            </li>
            <li>
              If we or our subsidiaries are involved in a merger, acquisition or
              asset sale, your Personal Data may be transferred.
            </li>
            <li>to our subsidiaries and affiliates </li>
            <li>with your consent in any other cases </li>
          </ul>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Security of Data
          </h2>

          <p className="mt-4 font-light text-gray-700">
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Your Data Protection Rights Under General Data Protection Regulation
            (GDPR)
          </h2>

          <p className="mt-4 font-light text-gray-700">
            If you are a resident of the European Union (EU) and European
            Economic Area (EEA), you have certain data protection rights,
            covered by GDPR. – See more at
            https://eur-lex.europa.eu/eli/reg/2016/679/oj
          </p>

          <p className="mt-4 font-light text-gray-700">
            We aim to take reasonable steps to allow you to correct, amend,
            delete, or limit the use of your Personal Data.
          </p>
          <p className="mt-4 font-light text-gray-700">
            If you wish to be informed what Personal Data we hold about you and
            if you want it to be removed from our systems, please email us at
            support@TBD.
          </p>
          <p className="mt-4 font-light text-gray-700">
            In certain circumstances, you have the following data protection
            rights:
          </p>
          <ul className="pl-10 mt-4 font-light text-gray-600 list-disc">
            <li>
              the right to access, update or to delete the information we have
              on you;
            </li>
            <li>
              the right of rectification. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete;
            </li>
            <li>
              the right to object. You have the right to object to our
              processing of your Personal Data;
            </li>
            <li>
              the right of restriction. You have the right to request that we
              restrict the processing of your personal information;
            </li>
            <li>
              the right to data portability. You have the right to be provided
              with a copy of your Personal Data in a structured,
              machine-readable and commonly used format;
            </li>
            <li>
              the right to withdraw consent. You also have the right to withdraw
              your consent at any time where we rely on your consent to process
              your personal information;
            </li>
          </ul>

          <p className="mt-4 font-light text-gray-700">
            Please note that we may ask you to verify your identity before
            responding to such requests. Please note, we may not able to provide
            Service without some necessary data.
          </p>
          <p className="mt-4 font-light text-gray-700">
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Your Data Protection Rights under the California Privacy Protection
            Act (CalOPPA)
          </h2>

          <p className="mt-4 font-light text-gray-700">
            CalOPPA is the first state law in the nation to require commercial
            websites and online services to post a privacy policy. The law’s
            reach stretches well beyond California to require a person or
            company in the United States (and conceivable the world) that
            operates websites collecting personally identifiable information
            from California consumers to post a conspicuous privacy policy on
            its website stating exactly the information being collected and
            those individuals with whom it is being shared, and to comply with
            this policy. – See more at:
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </p>

          <p className="mt-4 font-light text-gray-700">
            According to CalOPPA we agree to the following:
          </p>

          <ul className="pl-10 mt-4 font-light text-gray-600 list-disc">
            <li>users can visit our site anonymously;</li>
            <li>
              our Privacy Policy link includes the word “Privacy”, and can
              easily be found on the page specified above on the home page of
              our website;
            </li>
            <li>
              users will be notified of any privacy policy changes on our
              Privacy Policy Page;
            </li>
            <li>
              users are able to change or delete their personal information by
              emailing us at support@TBD.
            </li>
          </ul>

          <p className="mt-4 font-light text-gray-700">
            Our Policy on “Do Not Track” Signals:
          </p>

          <p className="mt-4 font-light text-gray-700">
            We honor Do Not Track signals and do not track, plant cookies, or
            use advertising when a Do Not Track browser mechanism is in place.
            Do Not Track is a preference you can set in your web browser to
            inform websites that you do not want to be tracked.
          </p>

          <p className="mt-4 font-light text-gray-700">
            You can enable or disable Do Not Track by visiting the Preferences
            or Settings page of your web browser.
          </p>

          {/* <p className="mt-4 font-light text-gray-700">
            Do Not Sell My Information: If you are a California resident and
            would like to know what personal information we collect and sell on
            you, or you wish to request that we do not sell your personal
            information; you may email us at support@TBD from an
            email address associated with your organization.
          </p> */}

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Service Providers
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), provide Service on our behalf,
            perform Service-related services or assist us in analysing how our
            Service is used.
          </p>

          <p className="mt-4 font-light text-gray-700">
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">Analytics </h4>

          <p className="mt-4 font-light text-gray-700">
            We may use third-party Service Providers to monitor and analyze the
            use of our Service.
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">
            Google Analytics
          </h4>

          <p className="mt-4 font-light text-gray-700">
            Google Analytics is a web analytics service offered by Google that
            tracks and reports website traffic. Google uses the data collected
            to track and monitor the use of our Service. This data is shared
            with other Google services. Google may use the collected data to
            contextualise and personalise the ads of its own advertising
            network.
          </p>

          <p className="mt-4 font-light text-gray-700">
            For more information on the privacy practices of Google, please
            visit the Google Privacy Terms web page:
            https://policies.google.com/privacy?hl=en
          </p>

          <p className="mt-4 font-light text-gray-700">
            We also encourage you to review the Google&apos;s policy for
            safeguarding your data:
            https://support.google.com/analytics/answer/6004245.
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">
            CI/CD tools
          </h4>

          <p className="mt-4 font-light text-gray-700">
            We may use third-party Service Providers to automate the development
            process of our Service.
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">
            CI/CD tools
          </h4>

          <p className="mt-4 font-light text-gray-700">
            GitHub is provided by GitHub, Inc.
          </p>

          <p className="mt-4 font-light text-gray-700">
            GitHub is a development platform to host and review code, manage
            projects, and build software.
          </p>

          <p className="mt-4 font-light text-gray-700">
            For more information on what data GitHub collects for what purpose
            and how the protection of the data is ensured, please visit GitHub
            Privacy Policy page:
            https://help.github.com/en/articles/github-privacy-statement.
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">
            Behavioral Remarketing
          </h4>

          <p className="mt-4 font-light text-gray-700">
            TBD LLC uses remarketing services to advertise on third party
            websites to you after you visited our Service. We and our
            third-party vendors use cookies to inform, optimise and serve ads
            based on your past visits to our Service.
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">
            Google Ads (AdWords)
          </h4>

          <p className="mt-4 font-light text-gray-700">
            Google Ads (AdWords) remarketing service is provided by Google Inc.
          </p>

          <p className="mt-4 font-light text-gray-700">
            You can opt-out of Google Analytics for Display Advertising and
            customize the Google Display Network ads by visiting the Google Ads
            Settings page: http://www.google.com/settings/ads
          </p>

          <p className="mt-4 font-light text-gray-700">
            Google also recommends installing the Google Analytics Opt-out
            Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your
            web browser. Google Analytics Opt-out Browser Add-on provides
            visitors with the ability to prevent their data from being collected
            and used by Google Analytics.
          </p>

          <p className="mt-4 font-light text-gray-700">
            For more information on the privacy practices of Google, please
            visit the Google Privacy Terms web page:
            https://policies.google.com/privacy?hl=en
          </p>

          <h4 className="mt-6 font-normal text-gray-700 text-md">Facebook </h4>

          <p className="mt-4 font-light text-gray-700">
            Facebook remarketing service is provided by Facebook Inc.
          </p>

          <p className="mt-4 font-light text-gray-700">
            You can learn more about interest-based advertising from Facebook by
            visiting this page: https://www.facebook.com/help/164968693837950
          </p>

          <p className="mt-4 font-light text-gray-700">
            To opt-out from Facebook&apos;s interest-based ads, follow these
            instructions from Facebook:
            https://www.facebook.com/help/568137493302217
          </p>

          <p className="mt-4 font-light text-gray-700">
            Facebook adheres to the Self-Regulatory Principles for Online
            Behavioural Advertising established by the Digital Advertising
            Alliance. You can also opt-out from Facebook and other participating
            companies through the Digital Advertising Alliance in the USA
            http://www.aboutads.info/choices/, the Digital Advertising Alliance
            of Canada in Canada http://youradchoices.ca/ or the European
            Interactive Digital Advertising Alliance in Europe
            http://www.youronlinechoices.eu/, or opt-out using your mobile
            device settings.
          </p>

          <p className="mt-4 font-light text-gray-700">
            For more information on the privacy practices of Facebook, please
            visit Facebook&apos;s Data Policy:
            https://www.facebook.com/privacy/explanation
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Payments
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g.
            payment processors).
          </p>

          <p className="mt-4 font-light text-gray-700">
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processors whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
          </p>

          <p className="mt-4 font-light text-gray-700">
            We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g.
            payment processors).
          </p>

          <p className="mt-4 font-light text-gray-700">
            The payment processors we work with are:
          </p>

          <p className="mt-4 font-light text-gray-700">
            Stripe: Their Privacy Policy can be viewed at:
            https://stripe.com/us/privacy
          </p>

          <p className="mt-4 font-light text-gray-700">
            Chargebee: Their Privacy Policy can be viewed at:
            https://www.chargebee.com/privacy
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Links to Other Sites
          </h2>

          <p className="mt-4 font-light text-gray-700">
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party&apos;s site. We strongly advise you to review the
            Privacy Policy of every site you visit.
          </p>

          <p className="mt-4 font-light text-gray-700">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Children&apos;s Privacy
          </h2>

          <p className="mt-4 font-light text-gray-700">
            Our Services are not intended for use by children under the age of
            18 (“Child” or “Children”).
          </p>

          <p className="mt-4 font-light text-gray-700">
            We do not knowingly collect personally identifiable information from
            Children under 18. If you become aware that a Child has provided us
            with Personal Data, please contact us. If we become aware that we
            have collected Personal Data from Children without verification of
            parental consent, we take steps to remove that information from our
            servers.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Changes to This Privacy Policy
          </h2>

          <p className="mt-4 font-light text-gray-700">
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>

          <p className="mt-4 font-light text-gray-700">
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update
            “effective date” at the top of this Privacy Policy.
          </p>

          <p className="mt-4 font-light text-gray-700">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>

          <h2 className="mt-8 text-lg font-semibold text-indigo-700">
            Contact Us
          </h2>

          <p className="mt-4 font-light text-gray-700">
            If you have any questions about this Privacy Policy, please contact
            us:
          </p>

          <p className="mt-4 font-light text-gray-700">
            By email: support@tbd.
          </p>
        </div>
      </div>
    </>
  );
}
